Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu_22_04"
  end

  config.vm.network "private_network", ip: "192.168.56.6"
  config.vm.synced_folder "./public", "/home/vagrant/public"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
